const updateAll = function() {
    tableObj.loadFromDataObject();
    compositeLoaderObj.updateReferenceCounter();
    xAxisInputObj.update();
    yAxisInputObj.update();
    lockAxesObj.update();
    opacityInputObj.update();
    smoothingInputObj.update();
    bpShiftInputObj.update();
    combineStrandsObj.update();
    separateColorsObj.update();
    colorTraceObj.update();
    enablePlotTooltipObj.update();
    showLegendObj.update();
    plotObj.updatePlot();
    legendObj.updateLegend();
    referenceLinesObj.updateReferenceLines();
    referenceLinesInputObj.update();
    nucleosomeSliderObj.updateNucleosomeSlider();
    nucleosomeSliderInputObj.update()
}